apiVersion: v2
appVersion: 1.5.7
description: diademiemi's sites
name: site
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - site
sources:
  - https://github.com/diademiemi/blahaj.sh
maintainers:
  - name: diademiemi
    email: emilia@diademiemi.me
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.1
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
